agentName: java
agentType: APM
title: 'Monitor your Java app'
introFilePath: 'src/install/java/intro.mdx'
agentConfigFilePath: 'src/install/config/agent-config/java-newrelic.yml'
appInfo:
  - optionType: deployment
    label: 'Where is your app deployed?'
    placeholder: 'My app is deployed on...'
    options:
      - value: 'appServer'
        displayName: 'an app server'
        logo: 'appServer'
        recommendedGuided: true
      - value: 'docker'
        displayName: 'in a Docker Container'
        logo: 'docker'
      - value: 'maven'
        displayName: 'Maven'
        logo: 'maven'
      - value: 'gradle'
        displayName: 'Gradle'
        logo: 'gradle'
      - value: 'aws'
        displayName: 'AWS Lambda'
        logo: 'awsLambda'
  - optionType: framework
    label: 'What framework are you using?'
    placeholder: 'My framework is...'
    options:
      - value: 'jetty'
        displayName: 'Jetty'
        logo: 'jetty'
        recommendedGuided: true
      - value: 'springboot'
        displayName: 'Spring Boot'
        logo: 'springboot'
        recommendedGuided: true
      - value: 'tomcat'
        displayName: 'Tomcat'
        logo: 'tomcat'
        recommendedGuided: true
      - value: 'wildfly'
        displayName: 'Wildfly'
        logo: 'wildfly'
        recommendedGuided: true
      - value: 'coldfusion'
        displayName: 'ColdFusion'
        logo: 'coldfusion'
      - value: 'geronimo'
        displayName: 'Geronimo'
        logo: 'geronimo'
      - value: 'glassfish'
        displayName: 'Glassfish'
        logo: 'glassfish'
      - value: 'grails'
        displayName: 'Grails'
        logo: 'grails'
      - value: 'jboss'
        displayName: 'JBoss'
        logo: 'jboss'
      - value: 'play'
        displayName: 'Play'
        logo: 'play'
      - value: 'solr'
        displayName: 'Solr'
        logo: 'solr'
      - value: 'tanuki'
        displayName: 'Tanuki Wrapper'
        logo: 'tanukiWrapper'
      - value: 'weblogic'
        displayName: 'WebLogic'
        logo: 'wildfly'
      - value: 'websphere'
        displayName: 'IBM WebSphere'
        logo: 'ibmWebSphere'
steps:
  - filePath: 'src/install/java/appInfo.mdx'
  - filePath: 'src/install/java/download/default.mdx'
  - filePath: 'src/install/java/agentConfig.mdx'
  - filePath: 'src/install/java/createDirectory.mdx'
  - filePath: 'src/install/java/moveDirectory.mdx'
  - filePath: 'src/install/java/frameworkInstallation/default.mdx'
    overrides:
      - filePath: 'src/install/java/frameworkInstallation/tomcat.mdx'
        selectedOptions:
          - optionType: framework
            options:
              - value: 'tomcat'
          - optionType: deployment
            options:
              - value: 'appServer'
whatsNextFilePath: 'src/install/java/whatsNext.mdx'
