agentName: java
agentType: APM
title: 'Monitor your java app'
introFilePath: 'src/install/java/intro.mdx'
agentConfigFilePath: 'src/install/config/agent-config/java-newrelic.yml'
appInfo:
  - optionType: deployment
    label: 'Where is your app deployed?'
    placeholder: 'My app is deployed on...'
    options:
      - value: 'maven'
        displayName: 'built with Maven'
        logo: 'maven'
      - value: 'docker'
        displayName: 'in a Docker Container'
        logo: 'docker'
      - value: 'applicationServer'
        displayName: 'on an application server'
        recommendedGuided: true
  - optionType: framework
    label: 'What framework are you using?'
    placeholder: 'My framework is...'
    options:
      - value: 'jetty'
        displayName: 'Jetty'
        logo: 'jetty'
      - value: 'tomcat'
        displayName: 'Tomcat'
        logo: 'tomcat'

steps:
  - filePath: 'src/install/java/createAnAccount.mdx'
  - filePath: 'src/install/java/appInfo.mdx'
  - filePath: 'src/install/java/download/default.mdx'
    overrides:
      - optionType: deployment
        overrideConfig:
          - value: 'applicationServer'
            filePath: 'src/install/java/download/applicationServer.mdx'
          - value: 'docker'
            filePath: 'src/install/java/download/docker.mdx'
      - optionType: framework
        overrideConfig:
          - value: 'tomcat'
            skip: true
  - filePath: 'src/install/java/agentConfig.mdx'
  - filePath: 'src/install/java/createDirectory.mdx'
  - filePath: 'src/install/java/moveDirectory.mdx'
  - filePath: 'src/install/java/frameworkInstallation/default.mdx'
    overrides:
      - optionType: framework
        overrideConfig:
          - value: 'tomcat'
            filePath: 'src/install/java/frameworkInstallation/tomcat.mdx'
whatsNextFilePath: 'src/install/java/whatsNext.mdx'
