agentName: Java
agentType: APM
title: 'Monitor your java app'
introFilePath: 'src/install/java/intro.mdx'
appInfoOptions:
  - optionType: deployment
    label: 'Where is your app deployed?'
    options:
      - value: 'applicationServer'
        displayName: 'on an application server'
        recommendGuided: true
      - value: 'maven'
        displayName: 'built with Maven'
      - value: 'docker'
        displayName: 'in a Docker Container'
  - optionType: framework
    label: 'What framework are you using?'
    options:
      - value: 'tomcat'
        displayName: 'Tomcat'
      - folderName: 'jetty'
        displayName: 'Jetty'
steps:
  - filePath: 'src/install/java/createAnAccount.mdx'
  - filePath: 'src/install/java/appInfo.mdx'
  - filePath: 'src/install/java/download/default.mdx'
    overrides:
      - optionType: deployment
        overrideConfig:
          - value: 'applicationServer'
            filePath: 'src/install/java/download/applicationServer.mdx'
            overrides:
              - type: 'framework'
                overrideConfig:
                  - value: 'tomcat'
                    skip: true
          - value: 'docker'
            filePath: 'src/install/java/download/docker.mdx'
  - filePath: 'src/install/java/agentConfig.mdx'
    overrides:
      - optionType: deployment
        overrideConfig:
          - value: 'docker'
            skip: true
  - filePath: 'src/install/java/createDirectory.mdx'
  - filePath: 'src/install/java/moveDirectory.mdx'
  - filePath: 'src/install/java/frameworkInstallation/default.mdx'
    overrides:
      - optionType: 'framework'
        overrideConfig:
          - value: 'tomcat'
            filePath: 'src/install/java/frameworkInstallation/tomcat.mdx'
whatsNextMdx: |
  Monitor your app data in New Relic and get comfortable with (the user interface)[].
