agentLanguage: Java
agentType: APM
title: 'Monitor your java app'
introFile: 'content/intro.mdx'
appInfoOptions:
  - type: deployment
    label: 'Where is your app deployed?'
    options:
      - value: 'applicationServer'
        displayName: 'on an application server'
        recommendGuided: true
      - value: 'maven'
        displayName: 'built with Maven'
      - value: 'docker'
        displayName: 'in a Docker Container'
  - type: framework
    label: 'What framework are you using?'
    options:
      - value: 'tomcat'
        displayName: 'Tomcat'
      - folderName: 'jetty'
        displayName: 'Jetty'
steps:
  - file: 'content/createAnAccount.mdx'
  - file: 'content/appInfo.mdx'
  - file: 'content/download/default.mdx'
    overrides:
      - type: deployment
        overrideConfig:
          - value: 'applicationServer'
            file: 'download/applicationServer.mdx'
            overrides:
              - type: 'framework'
                overrideConfig:
                  - value: 'tomcat'
                    skip: true
          - value: 'docker'
            file: 'download/docker.mdx'
  - file: 'agentConfig.mdx'
    overrides:
      - type: deployment
        overrideConfig:
          - value: 'docker'
            skip: true
  - file: 'createDirectory.mdx'
  - file: 'moveFiles.mdx'
  - file: 'frameworkInstallation/default.mdx'
    overrides:
      - type: 'framework'
        overrideConfig:
          - value: 'tomcat'
            file: 'frameworkInstallation/tomcat.mdx'
whatsNextMdx: |
  Monitor your app data in New Relic and get comfortable with (the user interface)[].
