title: New Relic security
path: /docs/new-relic-security
pages:
  - title: Data privacy
    pages:
      - title: Security controls for privacy
        path: /docs/security/new-relic-security/data-privacy/security-controls-privacy
  - title: Security bulletins
    pages:
      - title: Security for Heartbleed vulnerability
        path: /docs/security/new-relic-security/security-bulletins/security-heartbleed-vulnerability
  - title: Security and privacy
    path: /docs/security
