title: Security
children:
  - title: Security and privacy
    path: /docs
  - title: New Relic security
    children:
      - title: Data privacy
        children:
          - title: Security controls for privacy
            path: /docs/security/new-relic-security/data-privacy/security-controls-privacy
      - title: Security bulletins
        children:
          - title: Security for Heartbleed vulnerability
            path: /docs/security/new-relic-security/security-bulletins/security-heartbleed-vulnerability
