name: Send content to be translated

# TODO: uncomment when ready for this to run
# on:
# schedule:
# 6pm every Thursday
# - cron: '0 18 * * 4'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TRANSLATION_VENDOR_API_URL: ${{ secrets.TRANSLATION_VENDOR_API_URL }}
  TRANSLATION_VENDOR_PROJECT: ${{ secrets.TRANSLATION_VENDOR_PROJECT }}
  TRANSLATION_VENDOR_USER: ${{ secrets.TRANSLATION_VENDOR_USER }}
  TRANSLATION_VENDOR_SECRET: ${{ secrets.TRANSLATION_VENDOR_SECRET }}

jobs:
  fetch-content:
    name: Fetch translated content
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: TEST - install dependencies
        run: |
          rm package.json
          yarn add node-fetch aws-sdk form-data

      - name: Fetches translated content and deserializes
        run: node ./scripts/actions/check-job-progress.js

      - name: Commit translated files
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Your Name
          author_email: mail@example.com
          message: 'Your commit message'
          branch: some-branch
          add: 'src/i18n/content/**/*.mdx'

      - name: Create PR for translated files
        uses: peter-evans/create-pull-request@v3
