name: Send content to be translated

# TODO: uncomment when ready for this to run
# on:
# schedule:
# 6pm every Thursday
# - cron: '0 18 * * 4'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TRANSLATION_VENDOR_API_URL: ${{ secrets.TRANSLATION_VENDOR_API_URL }}
  TRANSLATION_VENDOR_PROJECT: ${{ secrets.TRANSLATION_VENDOR_PROJECT }}
  TRANSLATION_VENDOR_USER: ${{ secrets.TRANSLATION_VENDOR_USER }}
  TRANSLATION_VENDOR_SECRET: ${{ secrets.TRANSLATION_VENDOR_SECRET }}
  BOT_NAME: nr-opensource-bot
  BOT_EMAIL: opensource+bot@newrelic.com
  BRANCH_NAME: test-branch

jobs:
  fetch-content:
    name: Fetch translated content
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: TEST - install dependencies
        run: |
          rm package.json
          yarn add node-fetch aws-sdk form-data

      - name: Fetches translated content and deserializes
        run: |
          node ./scripts/actions/check-job-progress.js
          echo "this ran"

      - name: Commit changes
        id: commit-changes
        run: |
          git config --local user.email "${{ env.BOT_EMAIL }}"
          git config --local user.name "${{ env.BOT_NAME }}"
          git checkout -b "translate/${{ GITHUB_RUN_ID }}"
          git add ./src/i18n/content
          git commit -m 'chore: add translations'
          echo "::set-output name=commit::true"

      - name: Push Commit
        if: steps.commit-changes.outputs.commit == 'true'
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.OPENSOURCE_BOT_TOKEN }}
          branch: translate/${{ GITHUB_RUN_ID }}
