name: Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  create-release:
    name: Create Github release
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get-tag.outputs.tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get release tag
        id: get-tag
        run: |
          MERGES=$(gh pr list -B main -s closed -L 9999 | wc -L | awk '{print $1}')
          echo "::set-output name=tag::release-$MERGES"

      - name: Create release
        run: gh release create ${{ steps.get-tag.outputs.tag }}

  newrelic:
    name: New Relic deployment marker
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - name: Create New Relic deployment marker
        uses: newrelic/deployment-marker-action@v1
        with:
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          accountId: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
          applicationId: ${{ secrets.NEW_RELIC_APPLICATION_ID }}
          revision: ${{ needs.create-release.outputs.tag }}
