name: Release

on:
  pull_request:
    types:
      - main
    branches:
      - main

jobs:
  newrelic:
    name: New Relic deployment marker
    runs-on: ubuntu-latest
    steps:
      - name: Set release version from tag
        run: echo "RELEASE_VERSION=${{ GITHUB_REF:10 }}" >> $GITHUB_ENV

      - name: Create New Relic deployment marker
        uses: newrelic/deployment-marker-action@v1
        with:
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          accountId: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
          applicationId: ${{ secrets.NEW_RELIC_APPLICATION_ID }}
          revision: ${{ env.RELEASE_VERSION }}
