name: Send content to be translated

on:
  schedule:
    # 6pm every Thursday
    - cron: '0 18 * * 4'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  send-content:
    name: Send content
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install required dependencies
        run: |
          rm package.json
          yarn add aws-sdk

      - name: Get content to be translated and send to vendor
        run: node ./scripts/actions/fetch-translation-queue.js
