name: Send content to be translated

# TODO: uncomment when ready for this to run
# on:
  # schedule:
    # 6pm every Thursday
    # - cron: '0 18 * * 4'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TRANSLATION_VENDOR_API_URL: ${{ secrets.TRANSLATION_VENDOR_API_URL }}
  TRANSLATION_VENDOR_PROJECT: ${{ secrets.TRANSLATION_VENDOR_PROJECT }}
  TRANSLATION_VENDOR_USER: ${{ secrets.TRANSLATION_VENDOR_USER }}
  TRANSLATION_VENDOR_SECRET: ${{ secrets.TRANSLATION_VENDOR_SECRET }}

jobs:
  send-content:
    name: Send content
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      # TODO: uncomment when we need all our dependencies
      # - name: Get yarn cache directory path
        # id: yarn-cache-dir-path
        # run: echo "::set-output name=dir::$(yarn cache dir)"

      # - name: Cache dependencies
        # uses: actions/cache@v2
        # with:
          # path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          # key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          # restore-keys: |
            # ${{ runner.os }}-yarn-

      # - name: Install dependencies
        # run: yarn install --frozen-lockfile

      # TODO: remove (or add the dependencies needed)
      - name: TEST - install dependencies
        run: |
          rm package.json
          yarn add node-fetch aws-sdk form-data

      - name: Get content to be translated and send to vendor
        run: node ./scripts/actions/send-and-update-translation-queue.js
