name: Validate Pull Request

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    name: Gatsby Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
